version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    user: root
    ports:
      - "8082:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/plugins.txt:/usr/share/jenkins/ref/plugins.txt
      - ./jenkins/scripts:/usr/share/jenkins/ref/init.groovy.d
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      JENKINS_OPTS: --prefix=/jenkins
    restart: unless-stopped
    networks:
      - vdi-network

networks:
  vdi-network:
    external: true

volumes:
  jenkins_data:
